import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Sidebar from "@/components/sidebar";
import MobileSidebar from "@/components/mobile-sidebar";
import { ClerkProvider } from "@clerk/nextjs";
import AddButton from "@/components/add-button";
import { FormModal } from "@/components/modals/form-modal";
import { Toaster } from "@/components/ui/toaster";
import ArchivedDrawer from "@/components/archived-drawer";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <body className={roboto.className}>
            <MobileSidebar />
            <AddButton />
            <ArchivedDrawer />
            <FormModal />
            {children}
            <Toaster />
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
